[package]
name = "urlqstring"
version = "0.2.0"
authors = ["zmant <zmant724@aliyun.com>"]
license = "MIT"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
